// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreLib.Models;

public partial class Apiaudit
{
    public int ApiauditId { get; set; }

    public string SessionNkey { get; set; }

    public int SystemActivityId { get; set; }

    public int ParentSystemActivityId { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUserNkey { get; set; }

    public string CreateForUserNkey { get; set; }

    public int? ClientKey { get; set; }

    public int? AccountKey { get; set; }

    public int? SubAccountKey { get; set; }

    public int? MemberKey { get; set; }

    public int? SubscriberKey { get; set; }

    public string MemberPlatformCode { get; set; }

    public virtual ApiauditPayload ApiauditPayload { get; set; }

    public virtual ApiauditPcp ApiauditPcp { get; set; }

    public virtual SystemActivity ParentSystemActivity { get; set; }

    public virtual SystemActivity SystemActivity { get; set; }
}