// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreLib.Models;

public partial class ApiauditPcp
{
    public int ApiauditPcpid { get; set; }

    public int ApiauditId { get; set; }

    public int MemberKey { get; set; }

    public string CurrentSupplierLocationNkey { get; set; }

    public int CurrentPcpkey { get; set; }

    public string CurrentPcpname { get; set; }

    public string NewSupplierLocationNkey { get; set; }

    public int NewPcpkey { get; set; }

    public string NewPcpname { get; set; }

    public DateTime EffDate { get; set; }

    public bool IsProcessedFlag { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Apiaudit Apiaudit { get; set; }
}