// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreLib.Models;

public partial class ApiauditPayload
{
    public int ApiauditPayloadId { get; set; }

    public int ApiauditId { get; set; }

    public string ApiendPointDetail { get; set; }

    public string RequestPayloadHtml { get; set; }

    public string ResponseResultHtml { get; set; }

    public string ResponseCode { get; set; }

    public virtual Apiaudit Apiaudit { get; set; }
}