// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreLib.Models;

public partial class SystemActivity
{
    public int SystemActivityId { get; set; }

    public string SystemActivityName { get; set; }

    public string SystemActivityTypeNkey { get; set; }

    public bool IsActiveFlag { get; set; }

    public virtual ICollection<Apiaudit> ApiauditParentSystemActivities { get; set; } = [];

    public virtual ICollection<Apiaudit> ApiauditSystemActivities { get; set; } = [];
}