namespace CoreLib.Application.Common.DBQueries
{
    public partial class SqlQueries
    {
		public const string ICPGetClientPlatformQuery = @"
			SELECT 
			CASE 
				WHEN Count(TBL.ENRL_PLATFORM_NM) > 1 THEN 'MIXED'
				WHEN Count(TBL.ENRL_PLATFORM_NM) = 1 THEN
					CASE WHEN MAX(TBL.ENRL_PLATFORM_NM) = 'CoreSF' THEN 'CSF'
						WHEN MAX(TBL.ENRL_PLATFORM_NM) = 'CoreFI' THEN 'CFI'
					END 
			END AS PLATFORM_INDICATOR
			FROM (SELECT DISTINCT C.ENRL_PLATFORM_NM
				  FROM [dbo].[ICP_CUST] A
				  JOIN
					(SELECT SRC_CUST_ID, MIN(SNPSHT_DT) SNPSHT_DT,DATEADD(month, 1, MIN(SNPSHT_DT)) SNPSHT_DT2 
						FROM [dbo].ICP_GRP G WHERE G.SRC_CUST_ID = '@ClientId' 
						AND G.SNPSHT_DT >= DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0) 
						AND G.DATA_SRC_CD = 'FOS' GROUP BY G.SRC_CUST_ID) DT
					ON DT.SRC_CUST_ID = A.SRC_CUST_ID 
				LEFT JOIN  [dbo].[ICP_GRP] B 
					ON A.SRC_CUST_ID = B.SRC_CUST_ID AND  B.DATA_SRC_CD='FOS' 
						AND (DT.SNPSHT_DT = B.SNPSHT_DT OR DT.SNPSHT_DT2 = B.SNPSHT_DT)
				LEFT JOIN [dbo].[ICP_GRP_PRPKG_CVG] C  
					ON C.SRC_CUST_ID =  DT.SRC_CUST_ID 
						AND C.DATA_SRC_CD = 'FOS' 
						AND B.SRC_GRP_NO = C.SRC_GRP_NO 
						AND (DT.SNPSHT_DT = C.SNPSHT_DT OR DT.SNPSHT_DT2 = C.SNPSHT_DT)
						AND C.ENRL_PLATFORM_NM in ('CoreFI', 'CoreSF')
				WHERE
					(A.SNPSHT_DT = CAST(DT.SNPSHT_DT AS datetime) OR A.SNPSHT_DT = CAST(DT.SNPSHT_DT2 AS datetime))
					AND A.SRC_CUST_ID =  DT.SRC_CUST_ID
				GROUP BY C.ENRL_PLATFORM_NM ) TBL";
    }
}
